intg: Remove bashism from intgcheck-prepare
env variable UID is not defined in all shells (eg. dash)
We also need to move invocation of "id -u" before nss_wraper
is enabled otherwise we would get root instead of real user.

=================================== FAILURES ===================================
________________________ test_kcm_mem_init_list_destroy ________________________
Traceback (most recent call last):
  File "/home/build/sssd/src/tests/intg/test_kcm.py", line 198, in test_kcm_mem_init_list_destroy
    kcm_init_list_destroy(testenv)
  File "/home/build/sssd/src/tests/intg/test_kcm.py", line 183, in kcm_init_list_destroy
    exp_ccname = testenv.ccname()
  File "/home/build/sssd/src/tests/intg/test_kcm.py", line 45, in ccname
    my_uid = self.my_uid()
  File "/home/build/sssd/src/tests/intg/test_kcm.py", line 41, in my_uid
    return int(s_myuid)
ValueError: invalid literal for int() with base 10: ''

And we already use different approach in top level Makefile.am
3488)      $(INTGCHECK_CONFIGURE_FLAGS) \
3489)      CFLAGS="$$CFLAGS $(AM_CFLAGS) -DKCM_PEER_UID=$$(id -u)"; \
3490)  $(MAKE) $(AM_MAKEFLAGS) ; \

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>