CACHE_REQ: Avoid using of uninitialized value
Commit 4ef0b19a introduced the following warning, as "req" may be used
without being initialized:
src/responder/common/cache_req/cache_req_search.c:
     In function 'cache_req_search_done':
src/responder/common/cache_req/cache_req_search.c:467:9:
     error: 'req' may be used uninitialized in this function
     [-Werror=maybe-uninitialized]
         tevent_req_error(req, ret);
         ^
src/responder/common/cache_req/cache_req_search.c:424:24:
     note: 'req' was declared here
     struct tevent_req *req;
                        ^
cc1: all warnings being treated as errors

In order to fix the issue above, let's just allocate tmp_ctx after "req"
is already set.

Related:
https://pagure.io/SSSD/sssd/issue/3362

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
Co-Author: Lukáš Slebodník <lslebodn@redhat.com>
Reviewed-by: Sumit Bose <sbose@redhat.com>