ipa_selinux: Fix warning may be used uninitialized
src/providers/ipa/ipa_selinux.c: In function 'ipa_selinux_handler_done':
src/providers/ipa/ipa_selinux.c:927:16: error: 'sci' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     state->sci = sci;
                ^
src/providers/ipa/ipa_selinux.c:333:33: note: 'sci' was declared here
     struct selinux_child_input *sci;
                                 ^
cc1: all warnings being treated as errors

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit befd8f4639ecef8185e82092beae801d68fa7eae)