test_dyndns: Use different talloc context in wrapped functions.
Real functions use own allocation strategy. We use talloc in wrapped functions.
But wrapped functions should not use global_talloc_context,
leak_check_teardown will report false positive memory leaks.

  leak_check_teardown()
  ./src/tests/cmocka/test_dyndns.c:378: error: Failure!
  [  FAILED  ] dyndns_test_ok_dyndns_test_teardown

Reviewed-by: Jakub Hrozek <jhrozek@redhat.com>
(cherry picked from commit 12e7e87ccbae0d5c2f338cd019ca51556cbcd3ae)