intg: fix configure failure with strict cflags
The warning -Wstrict-prototypes is a part of AM_CFLAGS which was appended
for CFLAGS in make target intgcheck-prepare. And combination with
strict CFLAGS in environment variable (e.g. -Werror) caused failures.

sh$ CFLAGS="-Werror" make intgcheck-prepare

checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/build/sssd/ci-build-debug/intg/bld':
configure: error: C compiler cannot create executables

configure:3719: checking whether the C compiler works
configure:3741: gcc -g3 -O2 -Werror -D_FILE_OFFSET_BITS=64
                -D_LARGEFILE_SOURCE -Wall -Wshadow -Wstrict-prototypes
                -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings
                -Wundef -Werror-implicit-function-declaration
                -Winit-self -Wmissing-include-dirs -fno-strict-aliasing
                -std=gnu99 -DKCM_PEER_UID=1000   conftest.c  >&5
conftest.c:11:1: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 main ()
 ^~~~
cc1: all warnings being treated as errors

Reviewed-by: Pavel Březina <pbrezina@redhat.com>